namePrefix: staging-
commonLabels:
  environment: staging
bases:
- ../../base
patches:
- image.yaml
- replica_count.yaml
configMapGenerator:
- name: index
  behavior: replace
  files:
  - configs/index.html
